// The opcode map. Experimenting with different opcode maps can be done by changing this file only.

typedef enum logic [7:0] {
	OPCODE_TRAP =         8'h00, // trap
	OPCODE_SUB_XL_DIR =   8'h01, // sub xl, mm
	OPCODE_SUB_XL_SPREL = 8'h02, // sub xl, (n, sp)
	OPCODE_SUB_XL_ZREL =  8'h03, // sub xl, (nn, sp)
	OPCODE_SUB_XL_ZL =    8'h04, // sub xl, zl
	OPCODE_SUB_XL_XH =    8'h05, // sub xl, xh
	OPCODE_SUB_XL_YL =    8'h06, // sub xl, yl
	OPCODE_SUB_XL_YH =    8'h07, // sub xl, yh
	OPCODE_NOP =          8'h08, // nop
	OPCODE_SBC_XL_DIR =   8'h09, // sbc xl, mm
	OPCODE_SBC_XL_SPREL = 8'h0a, // sbc xl, (n, sp)
	OPCODE_SBC_XL_ZREL =  8'h0b, // sbc xl, (nn, sp)
	OPCODE_SBC_XL_ZL =    8'h0c, // sbc xl, zl
	OPCODE_SBC_XL_XH =    8'h0d, // sbc xl, xh
	OPCODE_SBC_XL_YL =    8'h0e, // sbc xl, yl
	OPCODE_SBC_XL_YH =    8'h0f, // sub xl, yh
	OPCODE_ADD_XL_IMMD =  8'h10, // add xl, #i
	OPCODE_ADD_XL_DIR =   8'h11, // add xl, mm
	OPCODE_ADD_XL_SPREL = 8'h12, // add xl, (n, sp)
	OPCODE_ADD_XL_ZREL =  8'h13, // add xl, (nn, sp)
	OPCODE_ADD_XL_ZL =    8'h14, // add xl, zl
	OPCODE_ADD_XL_XH =    8'h15, // add xl, xh
	OPCODE_ADD_XL_YL =    8'h16, // add xl, yl
	OPCODE_ADD_XL_YH =    8'h17, // add xl, yh
	OPCODE_ADC_XL_IMMD =  8'h18, // adc xl, #i
	OPCODE_ADC_XL_DIR =   8'h19, // adc xl, mm
	OPCODE_ADC_XL_SPREL = 8'h1a, // adc xl, (n, sp)
	OPCODE_ADC_XL_ZREL =  8'h1b, // adc xl, (nn, sp)
	OPCODE_ADC_XL_ZL =    8'h1c, // adc xl, zl
	OPCODE_ADC_XL_XH =    8'h1d, // adc xl, xh
	OPCODE_ADC_XL_YL =    8'h1e, // adc xl, yl
	OPCODE_ADC_XL_YH =    8'h1f, // adc xl, yh
	OPCODE_CP_XL_IMMD =   8'h20, // cp xl, #i
	OPCODE_CP_XL_DIR =    8'h21, // cp xl, mm
	OPCODE_CP_XL_SPREL =  8'h22, // cp xl, (n, sp)
	OPCODE_CP_XL_ZREL =   8'h23, // cp xl, (nn, sp)
	OPCODE_CP_XL_ZL =     8'h24, // cp xl, zl
	OPCODE_CP_XL_XH =     8'h25, // cp xl, xh
	OPCODE_CP_XL_YL =     8'h26, // cp xl, yl
	OPCODE_CP_XL_YH =     8'h27, // cp xl, yh
	OPCODE_OR_XL_IMMD =   8'h28, // or xl, #i
	OPCODE_OR_XL_DIR =    8'h29, // or xl, mm
	OPCODE_OR_XL_SPREL =  8'h2a, // or xl, (n, sp)
	OPCODE_OR_XL_ZREL =   8'h2b, // or xl, (nn, sp)
	OPCODE_OR_XL_ZL =     8'h2c, // or xl, zl
	OPCODE_OR_XL_XH =     8'h2d, // or xl, xh
	OPCODE_OR_XL_YL =     8'h2e, // or xl, yl
	OPCODE_OR_XL_YH =     8'h2f, // or xl, yh
	OPCODE_AND_XL_IMMD =  8'h30, // and xl, #i
	OPCODE_AND_XL_DIR =   8'h31, // and xl, mm
	OPCODE_AND_XL_SPREL = 8'h32, // and xl, (n, sp)
	OPCODE_AND_XL_ZREL =  8'h33, // and xl, (nn, sp)
	OPCODE_AND_XL_ZL =    8'h34, // and xl, zl
	OPCODE_AND_XL_XH =    8'h35, // and xl, xh
	OPCODE_AND_XL_YL =    8'h36, // and xl, yl
	OPCODE_AND_XL_YH =    8'h37, // and xl, yh
	OPCODE_XOR_XL_IMMD =  8'h38, // xor xl, #i
	OPCODE_XOR_XL_DIR =   8'h39, // xor xl, mm
	OPCODE_XOR_XL_SPREL = 8'h3a, // xor xl, (n, sp)
	OPCODE_XOR_XL_ZREL =  8'h3b, // xor xl, (nn, sp)
	OPCODE_XOR_XL_ZL =    8'h3c, // xor xl, zl
	OPCODE_XOR_XL_XH =    8'h3d, // xor xl, xh
	OPCODE_XOR_XL_YL =    8'h3e, // xor xl, yl
	OPCODE_XOR_XL_YH =    8'h3f, // xor xl, yh
	OPCODE_SRL_DIR =      8'h40, // srl mm
	OPCODE_SRL_SPREL =    8'h41, // srl (n, sp)
	OPCODE_SRL_XL =       8'h42, // srl xl
	OPCODE_SRL_YREL =     8'h43, // srl (n, y)
	OPCODE_SLL_DIR =      8'h44, // sll mm
	OPCODE_SLL_SPREL =    8'h45, // sll (n, sp)
	OPCODE_SLL_XL =       8'h46, // sll xl
	OPCODE_SLL_YREL =     8'h47, // sll (n, y)
	OPCODE_RRC_DIR =      8'h48, // rrc mm
	OPCODE_RRC_SPREL =    8'h49, // rrc (n, sp)
	OPCODE_RRC_XL =       8'h4a, // rrc xl
	OPCODE_RRC_YREL =     8'h4b, // rrc (n, y)
	OPCODE_RLC_DIR =      8'h4c, // rlc mm
	OPCODE_RLC_SPREL =    8'h4d, // rlc (n, sp)
	OPCODE_RLC_XL =       8'h4e, // rlc xl
	OPCODE_RLC_YREL =     8'h4f, // rlc (n, y)
	OPCODE_INC_DIR =      8'h50, // inc mm
	OPCODE_INC_SPREL =    8'h51, // inc (n, sp)
	OPCODE_INC_XL =       8'h52, // inc xl
	OPCODE_INC_YREL =     8'h53, // inc (n, y)
	OPCODE_DEC_DIR =      8'h54, // dec mm
	OPCODE_DEC_SPREL =    8'h55, // dec (n, sp)
	OPCODE_DEC_XL =       8'h56, // dec xl
	OPCODE_DEC_YREL =     8'h57, // dec (n, y)
	OPCODE_CLR_DIR =      8'h58, // clr mm
	OPCODE_CLR_SPREL =    8'h59, // clr (n, sp)
	OPCODE_CLR_XL =       8'h5a, // clr xl
	OPCODE_CLR_YREL =     8'h5b, // clr (n, y)
	OPCODE_TST_DIR =      8'h5c, // tst mm
	OPCODE_TST_SPREL =    8'h5d, // tst (n, sp)
	OPCODE_TST_XL =       8'h5e, // tst xl
	OPCODE_TST_YREL =     8'h5f, // tst (n, y)
	OPCODE_PUSH_DIR =     8'h60, // push mm
	OPCODE_PUSH_SPREL =   8'h61, // push (n, sp)
	OPCODE_PUSH_XL =      8'h62, // push xl
	OPCODE_PUSH_YREL =    8'h63, // push (n, y)
	OPCODE_JP_IMMD =      8'h64, // jp #ii
	OPCODE_JP_Y =         8'h65, // jp y
	OPCODE_CALL_IMMD =    8'h66, // call #ii
	OPCODE_CALL_Y =       8'h67, // call y
	OPCODE_XCHB_XL_MM_0 = 8'h68, // xchb xl, mm, #0
	OPCODE_XCHB_XL_MM_1 = 8'h69, // xchb xl, mm, #1
	OPCODE_XCHB_XL_MM_2 = 8'h6a, // xchb xl, mm, #2
	OPCODE_XCHB_XL_MM_3 = 8'h6b, // xchb xl, mm, #3
	OPCODE_XCHB_XL_MM_4 = 8'h6c, // xchb xl, mm, #4
	OPCODE_XCHB_XL_MM_5 = 8'h6d, // xchb xl, mm, #5
	OPCODE_XCHB_XL_MM_6 = 8'h6e, // xchb xl, mm, #6
	OPCODE_XCHB_XL_MM_7 = 8'h6f, // xchb xl, mm, #7
	OPCODE_LDW_Y_SP =     8'h70, // ld y, sp
	OPCODE_SUBW_Y_DIR =   8'h71, // subw y, mm
	OPCODE_SUBW_Y_SPREL = 8'h72, // subw y, (n, sp)
	OPCODE_SUBW_Y_X =     8'h73, // subw y, x
	OPCODE_LDW_ISPREL_Y = 8'h74, // ldw ((sp, n)), y
	OPCODE_SBCW_Y_DIR =   8'h75, // sbcw y, mm
	OPCODE_SBCW_Y_SPREL = 8'h76, // sbcw y, (n, sp)
	OPCODE_SBCW_Y_X =     8'h77, // sbcw y, x
	OPCODE_ADDW_Y_IMMD =  8'h78, // addw y, #ii
	OPCODE_ADDW_Y_DIR =   8'h79, // addw y, mm
	OPCODE_ADDW_Y_SPREL = 8'h7a, // addw y, (n, sp)
	OPCODE_ADDW_Y_X =     8'h7b, // addw y, x
	OPCODE_ADCW_Y_IMMD =  8'h7c, // adcw y, #ii
	OPCODE_ADCW_Y_DIR =   8'h7d, // adcw y, mm
	OPCODE_ADCW_Y_SPREL = 8'h7e, // adcw y, (n, sp)
	OPCODE_ADCW_Y_X =     8'h7f, // adcw y, x
	OPCODE_LD_XL_IMMD =   8'h80, // ld xl, #i
	OPCODE_LD_XL_DIR =    8'h81, // ld xl, mm
	OPCODE_LD_XL_SPREL =  8'h82, // ld xl, (n, sp)
	OPCODE_LD_XL_ZREL =   8'h83, // ld xl, (nn, z)
	OPCODE_LD_XL_IY =     8'h84, // ld xl, (y)
	OPCODE_LD_XL_YREL =   8'h85, // ld xl, (n, y)
	OPCODE_LD_XL_XH =     8'h86, // ld xl, xh
	OPCODE_LD_XL_YL =     8'h87, // ld xl, yl
	OPCODE_LD_XL_YH =     8'h88, // ld xl, yh
	OPCODE_LD_XL_ZL =     8'h89, // ld xl, zl
	OPCODE_LD_XL_ZH =     8'h8a, // ld xl, zh
	OPCODE_LD_DIR_XL =    8'h8b, // ld mm, zh
	OPCODE_LD_SPREL_XL =  8'h8c, // ld (n, sp), zh
	OPCODE_LD_ZREL_XL =   8'h8d, // ld (nn, z), zh
	OPCODE_LD_IY_XL =     8'h8e, // ld (y), xl
	OPCODE_LD_YREL_XL =   8'h8f, // ld (n, y), xl
	OPCODE_PUSH_IMMD =    8'h90, // push #i
	OPCODE_XCH_XL_SPREL = 8'h91, // xch	xl, (n, sp)
	OPCODE_XCH_XL_IY =    8'h92, // xch	xl, (y)
	OPCODE_XCH_YL_YH =    8'h93, // xch	yl, yh
	OPCODE_ALTACC4 =      8'h94, // altacc''''
	OPCODE_ROT_XL_IMMD =  8'h95, // rot xl, #i
	OPCODE_SRA_XL =       8'h96, // sra xl
	OPCODE_DA_XL =        8'h97, // da xl
	OPCODE_BOOL_XL =      8'h98, // bool xl
	OPCODE_POP_XL =       8'h99, // pop xl
	OPCODE_THRD_XL =      8'h9a, // thrd xl
	OPCODE_CAX_IY_ZL_XL = 8'h9b, // cax (y), zl, xl
	OPCODE_SWAPOP =       8'h9c, // swapop (prefix)
	OPCODE_ALTACC1 =      8'h9d, // altacc (prefix)
	OPCODE_ALTACC2 =      8'h9e, // altacc' (prefix)
	OPCODE_ALTACC3 =      8'h9f, // altacc'' (prefix)
	OPCODE_CLRW_DIR =     8'ha0, // clrw mm
	OPCODE_CLRW_SPREL =   8'ha1, // clrw (n, sp)
	OPCODE_CLRW_ZREL =    8'ha2, // clrw (nn, z)
	OPCODE_CLRW_Y =       8'ha3, // clrw y
	OPCODE_INCW_DIR =     8'ha4, // incw mm
	OPCODE_INCW_SPREL =   8'ha5, // incw (n, sp)
	OPCODE_INCW_ZREL =    8'ha6, // incw (nn, z)
	OPCODE_INCW_Y =       8'ha7, // incw y
	OPCODE_ADCW_DIR =     8'ha8, // adcw mm
	OPCODE_ADCW_SPREL =   8'ha9, // adcw (n, sp)
	OPCODE_ADCW_ZREL =    8'haa, // adcw (nn, z)
	OPCODE_ADCW_Y =       8'hab, // adcw y
	OPCODE_SBCW_DIR =     8'hac, // sbcw mm
	OPCODE_SBCW_SPREL =   8'had, // sbcw (n, sp)
	OPCODE_SBCW_ZREL =    8'hae, // sbcw (nn, z)
	OPCODE_SBCW_Y =       8'haf, // sbcw y
	OPCODE_PUSHW_DIR =    8'hb0, // pushw mm
	OPCODE_PUSHW_SPREL =  8'hb1, // pushw (n, sp)
	OPCODE_PUSHW_ZREL =   8'hb2, // pushw (nn, z)
	OPCODE_PUSHW_Y =      8'hb3, // pushw y
	OPCODE_TSTW_DIR =     8'hb4, // tstw mm
	OPCODE_TSTW_SPREL =   8'hb5, // tstw (n, sp)
	OPCODE_TSTW_ZREL =    8'hb6, // tstw (nn, z)
	OPCODE_TSTW_Y =       8'hb7, // tstw y
	OPCODE_MSK_IY_XL_IMMD = 8'hb8, // msk (y), xl, #i
	OPCODE_MUL_Y =        8'hb9, // mul y
	OPCODE_RET =          8'hba, // ret
	OPCODE_RETI =         8'hbb, // reti
	OPCODE_MAD_X_DIR_YL = 8'hbc, // mad x, mm, yl
	OPCODE_MAD_X_SPREL_YL = 8'hbd, // mad x, (n, sp), yl
	OPCODE_MAD_X_ZREL_YL = 8'hbe, // mad x, (nn, z), yl
	OPCODE_MAD_X_IZ_YL =  8'hbf, // mad x, (z), yl
	OPCODE_LDW_Y_IMMD =   8'hc0, // ldw y, #ii
	OPCODE_LDW_Y_DIR   =  8'hc1, // ldw y, mm
	OPCODE_LDW_Y_SPREL =  8'hc2, // ldw y, (n, sp)
	OPCODE_LDW_Y_ZREL =   8'hc3, // ldw y, (nn, z)
	OPCODE_LDW_Y_YREL =   8'hc4, // ldw y, (n, y)
	OPCODE_LDW_Y_IY =     8'hc5, // ldw y, (y)
	OPCODE_LDW_Y_X =      8'hc6, // ldw y, x
	OPCODE_LDW_Y_D =      8'hc7, // ldw y, #d
	OPCODE_LDW_DIR_Y =    8'hc8, // ldw mm, y
	OPCODE_LDW_SPREL_Y =  8'hc9, // ldw (n, sp), y
	OPCODE_LDW_ZREL_Y =   8'hca, // ldw (nn, z), y
	OPCODE_LDW_X_Y =      8'hcb, // ldw x, y
	OPCODE_LDW_Z_Y =      8'hcc, // ldw z, y
	OPCODE_LDW_IY_X =     8'hcd, // ldw (y), x
	OPCODE_LDW_YREL_X =   8'hce, // ldw (n, y), x
	OPCODE_LDWI_IZ_IY =   8'hcf, // ldwi (z), (y)
	OPCODE_JR_D =         8'hd0, // jr #d
	OPCODE_DNJNZ_YH_D =   8'hd1, // dnjnz yh, #d
	OPCODE_JRZ_D =        8'hd2, // jrz #d
	OPCODE_JRNZ_D =       8'hd3, // jrnz #d
	OPCODE_JRC_D =        8'hd4, // jrc #d
	OPCODE_JRNC_D =       8'hd5, // jrnc #d
	OPCODE_JRN_D =        8'hd6, // jrn #d
	OPCODE_JRNN_D =       8'hd7, // jrnn #d
	OPCODE_ALTACC5 =      8'hd8, // altacc'''''
	OPCODE_JRNO_D =       8'hd9, // jrno #d
	OPCODE_JRSGE_D =      8'hda, // jrsge #d
	OPCODE_JRSLT_D =      8'hdb, // jrslt #d
	OPCODE_RESERVED_DC =  8'hdc,
	OPCODE_JRSLE_D =      8'hdd, // jrsle #d
	OPCODE_RESERVED_DE =  8'hde,
	OPCODE_JRLE_D =       8'hdf, // jrle #d
	OPCODE_SRLW_Y =       8'he0, // srlw y
	OPCODE_SLLW_Y =       8'he1, // sllw y
	OPCODE_RRCW_Y =       8'he2, // rrcw y
	OPCODE_RLCW_Y =       8'he3, // rlcw y
	OPCODE_SRAW_Y =       8'he4, // sraw y
	OPCODE_SLLW_Y_XL =    8'he5, // sllw y, xl
	OPCODE_RRCW_SPREL =   8'he6, // rrcw (n, sp)
	OPCODE_RLCW_SPREL =   8'he7, // rlcw (n, sp)
	OPCODE_PUSHW_IMMD =   8'he8, // pushw #ii
	OPCODE_POPW_Y =       8'he9, // popw y
	OPCODE_ADDW_SP_D =    8'hea, // addw sp, #d
	OPCODE_ADDW_Y_D =     8'heb, // addw y, #d
	OPCODE_XCH_F_SPREL =  8'hec, // xch f, (n, sp)
	OPCODE_LDI_IZ_IY =    8'hed, // ldi (z), (y)
	OPCODE_SEX_Y_XL =     8'hee, // sex y, xl
	OPCODE_ZEX_Y_XL =     8'hef, // zex y, xl
	OPCODE_ORW_Y_IMMD =   8'hf0, // orw y, #ii
	OPCODE_ORW_Y_DIR =    8'hf1, // orw y, mm
	OPCODE_ORW_Y_SPREL =  8'hf2, // orw y, (n, sp)
	OPCODE_ORW_Y_X =      8'hf3, // orw y, x
	OPCODE_XCHW_X_IY =    8'hf4, // xchw x, (y)
	OPCODE_XCHW_Y_SPREL = 8'hf5, // xchw y, (n, sp)
	OPCODE_INCNW_Y =      8'hf6, // incnw y
	OPCODE_DECW_SPREL =   8'hf7, // decw (n, sp)
	OPCODE_CPW_Y_IMMD =   8'hf8, // cpw y, #ii
	OPCODE_CAXW_IY_Z_X =  8'hf9, // caxw (y), z, x
	OPCODE_NEGW_Y =       8'hfa, // negw y
	OPCODE_BOOLW_Y =      8'hfb, // boolw y
	OPCODE_XORW_Y_IMMD =  8'hfc, // xorw y, #ii
	OPCODE_XORW_Y_DIR =   8'hfd, // xorw y, mm
	OPCODE_XORW_Y_SPREL = 8'hfe, // xorw y, (n, sp)
	OPCODE_XORW_Y_X =     8'hff  // xorw y, x
	} opcode_t;

